load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "E5810Client_lib",
    srcs = ["E5810Client.cpp"],
    hdrs = ["E5810Client.hpp"],
    deps = ["@boost.asio"],
)

cc_library(
    name = "SCPIInstruement_lib",
    srcs = ["SCPIInstrumentSimulator.cpp"],
    hdrs = ["SCPIInstrumentSimulator.hpp"],
    deps = [
        ":E5810Client_lib",
    ],
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [":SCPIInstruement_lib"],
)
